import { FormEvent, useEffect, useMemo, useState } from 'react';
import './App.css';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:3100/api/v2';

type User = { id: string; username: string; displayName: string; role: string };
type Site = { id: string; site_code?: string; siteCode?: string; name: string; road?: string; status?: string };
type EventItem = { id: string; timestamp: string; plate_number?: string; vehicle_type: string; direction?: string; detection_confidence?: number; watchlist?: boolean; watchlist_category?: string; site_code?: string; site_name?: string; camera_code?: string; camera_name?: string };
type Alert = { id: string; severity: string; title: string; description?: string; status: string; created_at: string; site_code?: string; site_name?: string; camera_code?: string; camera_name?: string };
type EdgeStatus = { status: string; camera_workers?: { count: number; items: Record<string, { state: string; connected: boolean; frames_received: number; frames_processed: number; frames_dropped: number; reconnects: number; events_created: number; queue_depth: number; last_error?: string | null }> }; sync?: { running: boolean; synced_total: number; failed_total: number; queue: { pending: number }; central: { connected: boolean } }; };

async function api(path: string, options: RequestInit = {}, token?: string) {
  const headers = new Headers(options.headers || {}); headers.set('Content-Type', 'application/json'); if (token) headers.set('Authorization', `Bearer ${token}`);
  const response = await fetch(`${API_URL}${path}`, { ...options, headers }); const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.error || body.detail || `Request failed (${response.status})`); return body;
}

function Login({ onLogin }: { onLogin: (token: string, user: User) => void }) {
  const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState('');
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); try { const result = await api('/auth/login', { method: 'POST', body: JSON.stringify({ username, password }) }); onLogin(result.token, result.user); } catch (e) { setError(e instanceof Error ? e.message : 'Login failed'); } };
  return <div className="login"><form onSubmit={submit} className="login-card"><div className="logo">QTS</div><h1>AVCLPR</h1><p>Government AI Vehicle Intelligence Platform</p><input placeholder="Username" value={username} onChange={e => setUsername(e.target.value)} autoComplete="username"/><input placeholder="Password" type="password" value={password} onChange={e => setPassword(e.target.value)} autoComplete="current-password"/><button>SECURE LOGIN</button>{error && <div className="error">{error}</div>}</form></div>;
}

function App() {
  const [token, setToken] = useState(() => sessionStorage.getItem('avclpr_token') || ''); const [user, setUser] = useState<User | null>(null); const [events, setEvents] = useState<EventItem[]>([]); const [alerts, setAlerts] = useState<Alert[]>([]); const [sites, setSites] = useState<Site[]>([]); const [edge, setEdge] = useState<EdgeStatus | null>(null); const [error, setError] = useState(''); const [lastRefresh, setLastRefresh] = useState<Date | null>(null);
  const load = async () => { if (!token) return; try { const [me, eventData, alertData, siteData, edgeData] = await Promise.all([api('/auth/me', {}, token), api('/events?limit=100', {}, token), api('/alerts?limit=50&status=active', {}, token), api('/sites', {}, token), api('/system/edge-status', {}, token)]); setUser(me.user); setEvents(eventData.events || []); setAlerts(alertData.alerts || []); setSites(siteData.sites || []); setEdge(edgeData); setError(''); setLastRefresh(new Date()); } catch (e) { setError(e instanceof Error ? e.message : 'Dashboard connection failed'); } };
  useEffect(() => { if (token) { sessionStorage.setItem('avclpr_token', token); load(); const timer = setInterval(load, 5000); return () => clearInterval(timer); } }, [token]);
  const logout = () => { sessionStorage.removeItem('avclpr_token'); setToken(''); setUser(null); };
  const acknowledge = async (id: string) => { try { await api(`/alerts/${id}/acknowledge`, { method: 'POST' }, token); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to acknowledge alert'); } };
  const workers = Object.entries(edge?.camera_workers?.items || {}); const onlineWorkers = workers.filter(([, value]) => value.connected).length; const watchlistEvents = events.filter(event => event.watchlist).length; const vehiclesToday = useMemo(() => events.length, [events]);
  if (!token) return <Login onLogin={(newToken, newUser) => { setToken(newToken); setUser(newUser); }} />;
  return <div className="app">
    <header className="topbar"><div><div className="brand">QTS <span>AVCLPR</span></div><div className="subtitle">AI-POWERED HIGHWAY MONITORING · VEHICLE INTELLIGENCE · ROAD SAFETY</div></div><div className="userbar"><span>{user?.displayName || user?.username} · {user?.role}</span><button onClick={logout}>LOG OUT</button></div></header>
    <section className="metrics"><Metric label="EVENTS LOADED" value={vehiclesToday}/><Metric label="ACTIVE ALERTS" value={alerts.length} danger={alerts.length > 0}/><Metric label="WATCHLIST MATCHES" value={watchlistEvents}/><Metric label="EDGE CAMERAS" value={`${onlineWorkers}/${workers.length}`}/><Metric label="CENTRAL DB" value={edge?.sync?.central?.connected ? 'ONLINE' : 'OFFLINE'} online={!!edge?.sync?.central?.connected}/><Metric label="OUTBOX" value={edge?.sync?.queue?.pending ?? 0}/></section>
    {error && <div className="banner error">{error}</div>}
    <main className="grid">
      <section className="panel wide"><PanelTitle title="ACTIVE ALERTS" subtitle="Watchlist and operational alerts" count={alerts.length}/>{alerts.length === 0 ? <Empty text="No active alerts"/> : <div className="alerts">{alerts.map(alert => <div className={`alert ${alert.severity}`} key={alert.id}><div><strong>{alert.title}</strong><span>{alert.description}</span><small>{alert.site_name || alert.site_code || 'SITE'} · {alert.camera_name || alert.camera_code || 'CAMERA'} · {new Date(alert.created_at).toLocaleString()}</small></div><div><b>{alert.severity.toUpperCase()}</b>{user && ['SUPER_ADMIN','NATIONAL_ADMIN','POLICE','INTELLIGENCE'].includes(user.role) && <button onClick={() => acknowledge(alert.id)}>ACKNOWLEDGE</button>}</div></div>)}</div>}</section>
      <section className="panel"><PanelTitle title="EDGE OPERATIONS" subtitle="RTSP → AI → Events → Sync"/>{workers.length === 0 ? <Empty text="No edge camera workers registered"/> : <div className="workers">{workers.map(([id, worker]) => <div className="worker" key={id}><div><span className={`dot ${worker.connected ? 'online' : 'offline'}`}/><strong>{id}</strong></div><span>{worker.state.toUpperCase()}</span><small>RX {worker.frames_received.toLocaleString()} · AI {worker.frames_processed.toLocaleString()} · DROP {worker.frames_dropped.toLocaleString()}</small><small>Events {worker.events_created} · Queue {worker.queue_depth} · Reconnects {worker.reconnects}</small>{worker.last_error && <small className="error-text">{worker.last_error}</small>}</div>)}</div>}<div className="sync"><span>Automatic sync</span><strong className={edge?.sync?.running ? 'green' : 'red'}>{edge?.sync?.running ? 'RUNNING' : 'STOPPED'}</strong><small>Synced {edge?.sync?.synced_total ?? 0} · Failed {edge?.sync?.failed_total ?? 0}</small></div></section>
      <section className="panel"><PanelTitle title="PILOT SITES" subtitle="Government highway deployment" count={sites.length}/>{sites.length === 0 ? <Empty text="No sites configured"/> : <div className="sites">{sites.map(site => <div className="site" key={site.id}><strong>{site.site_code || site.siteCode}</strong><span>{site.name}</span><small>{site.road || 'Road not specified'} · {site.status || 'active'}</small></div>)}</div>}</section>
      <section className="panel full"><PanelTitle title="LIVE VEHICLE EVENT FEED" subtitle="Latest events from central PostgreSQL" count={events.length}/><div className="table-wrap"><table><thead><tr><th>TIME</th><th>SITE</th><th>CAMERA</th><th>VEHICLE</th><th>PLATE</th><th>DIRECTION</th><th>CONFIDENCE</th><th>STATUS</th></tr></thead><tbody>{events.map(event => <tr key={event.id}><td>{new Date(event.timestamp).toLocaleTimeString()}</td><td>{event.site_code || event.site_name || '—'}</td><td>{event.camera_code || event.camera_name || '—'}</td><td>{event.vehicle_type}</td><td className="plate">{event.plate_number || 'UNREADABLE'}</td><td>{event.direction || 'UNKNOWN'}</td><td>{event.detection_confidence != null ? `${(event.detection_confidence * 100).toFixed(1)}%` : '—'}</td><td>{event.watchlist ? <span className="tag danger">{event.watchlist_category || 'WATCHLIST'}</span> : <span className="tag">NORMAL</span>}</td></tr>)}</tbody></table></div></section>
    </main><footer><span>QTS · AVCLPR Government Platform</span><span>Last refresh: {lastRefresh?.toLocaleTimeString() || '—'} · Offline edge buffering enabled</span></footer>
  </div>;
}
function Metric({ label, value, danger, online }: { label: string; value: string | number; danger?: boolean; online?: boolean }) { return <div className="metric"><span>{label}</span><strong className={danger ? 'red' : online ? 'green' : ''}>{value}</strong></div>; }
function PanelTitle({ title, subtitle, count }: { title: string; subtitle: string; count?: number }) { return <div className="panel-title"><div><h2>{title}</h2><p>{subtitle}</p></div>{count != null && <b>{count}</b>}</div>; }
function Empty({ text }: { text: string }) { return <div className="empty">{text}</div>; }
export default App;
